language: python
python:
  - "3.6"

services:
  - docker

install:
- docker run -d -it --name tbears-container -p 9000:9000 iconloop/tbears:1.4.0

script:
- python setup.py test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  #server: https://test.pypi.org/legacy/
  user: iconfoundation
  password: $Pypi_pw
  on:
    branch: master
