language: python
python:
- "3.6"

install:
- git clone "https://oauth2:$Gitlab_token@repo.theloop.co.kr/icon/icon-sdk/icon-mock-node.git"
- cd icon-sdk-java-test
- npm install
- node index.js &
- sleep 5
- cd ..

script:
- python setup.py test

before_deploy:
- rm -rf icon-sdk-java-test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  #server: https://test.pypi.org/legacy/
  user: iconfoundation
  password: $Pypi_pw
  on:
    branch: master
