name: publish to test pypi
on:
  workflow_dispatch:
    inputs:
      test_deploy:
        description: 'test deploy to https://test.pypi.org'
        required: false
        default: 'false'
      version:
        description: 'test version to publish'
        required: false

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Check event inputs
        run: |
          echo "::notice:: test_deploy=${{ github.event.inputs.test_deploy }}"
          echo "::notice:: version=${{ github.event.inputs.version }}"
      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]
      - name: Run Test
        run: |
          python -m pytest -ra

  test-deploy:
    needs: unittest
    if: github.event.inputs.test_deploy == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependency
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          echo "::notice:: pip list"
          pip list
      - name: Setup test version
        if: github.event.inputs.version != ''
        run: |
          TEST_VERSION=${{ github.event.inputs.version }}
          echo "::notice:: update version from $(cat VERSION) to ${TEST_VERSION}"
          echo ${TEST_VERSION} > VERSION
      - name: Cache dist
        id: dist_cache
        uses: actions/cache@v2
        with:
          path: ./dist
          key: ${{ runner.os }}-dist-${{ github.sha }}
      - name: Build package
        if: steps.dist_cache.outputs.cache-hit != 'true'
        run: |
          python setup.py sdist bdist_wheel
          echo "::notice:: ls -al dist"
          ls -al dist
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
